# 1. Use an official base image
FROM node:20-slim as Builder

# 2. Set the working directory inside the container
WORKDIR /app

# 3. Copy dependency files first (optimizes build caching)
COPY package*.json ./

# 4. Install dependencies
RUN npm install 

# 5. Copy the rest of your application code
COPY . .

# 5. Build โปรเจกต์ (ถ้าต้องการรัน preview ต้อง build ก่อน)
RUN npm run build

